### ISSUE TITLE
Provided link in client_url does not exist

### ISSUE THREAD

**Issue by gmichels** [OpenNMS/opennms-pagerduty-plugin#7]
Plugin sends a `client_url` to PagerDuty that does not exist

```
{
  "client": "OpenNMS",
  "client_url": "https://nms03.internal.opennms.com/opennms/alarm/detail.htm?id=864481",
  "description": "\n            Interface 64.2.142.111 is down.\n        ",
  "event_type": "trigger",
  "incident_key": "uei.opennms.org/nodes/interfaceDown::70:64.2.142.111",
  "service_key": "5e84cb63be324b8387f08ad49735f935"
}
```

![image](https://user-images.githubusercontent.com/7144329/94184706-4f657f00-fe72-11ea-90b9-ef04b4a95872.png)

**Comment by j-white** [comment]
OpenNMS deletes alarms shortly after being cleared, so it is expected that the links won't work some time.

This specific case should be mitigated by the fix for https://github.com/OpenNMS/opennms-pagerduty-plugin/issues/5
